/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************


#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."

#include "stm32f401xe_gpio.h"

#define BTN_PRESS 0
#endif

void delay(void)
{
    for (uint32_t i = 0; i < 500000; i++);
}


*Button-Controlled LED
*  the green LED is a user LED connected to ARDUINO® signal D13 corresponding to STM32 I/O PA5
*  user button is connected to the I/O PC13 (pin 2) of the STM32 microcontroller.



int main(void)
{



	GPIO_Handle_t GpioLed,GpioBtn;



    // Configure LED (PA5)
       GpioLed.pGPIOx = GPIOA;
       GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;        //LED-PA5
       GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;          //output mode
       GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
       GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
       GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

       // Configure Button (PC13)
       GpioBtn.pGPIOx = GPIOC;
       GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;      //User Button-PC13
       GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;          //input mode
       GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
       GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

       // Enable clocks
       GPIO_PeriClockControl(GPIOA, ENABLE);
       GPIO_PeriClockControl(GPIOC, ENABLE);

       // Initialize pins
       GPIO_Init(&GpioLed);
       GPIO_Init(&GpioBtn);


           Blink LED
               while (1)
               {
                   GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
                   delay();
               }


       while (1)
           {
               if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == BTN_PRESS)
               {
                   delay();  // Debounce delay
                   GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
               }
           }

           return 0;
}
*/

